<a href="https://colab.research.google.com/github/GiselleOAlmeida/python-univesp-ciencia-de-dados/blob/main/Semana02_Atividade_Proposta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução a Ciência de Dados - Univesp

##Exercício de apoio semana 2

###1 - Carregue as bibliotecas NumPy e Pandas

In [2]:
import numpy as np
import pandas as pd

###2 - Crie um NDArray com os seguintes valores [1, 2.5, 7, -78, -0.9, 130, 25]

In [4]:
dados=np.array([1, 2.5, 7, -78, -0.9, 130, 25])

In [5]:
dados.dtype

dtype('float64')

In [6]:
dados

array([  1. ,   2.5,   7. , -78. ,  -0.9, 130. ,  25. ])

###3 - Crie um NDArray com os valores de 0 a 10

In [13]:
dados2=np.array([0,1,2,3,4,5,6,7,8,9,10])

In [22]:
dados2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
dados3=np.arange(11)

In [24]:
dados3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###4 – Crie um NDArray de dimensão 2x5 com valores 1

In [16]:
dadosones=np.ones(1)

In [20]:
dadosones=np.ones((2,5))

In [21]:
dadosones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

###5 – Crie um NDArray com valores de 1 a 100, com intervalos de 3 em 3.

In [26]:
dados4=np.arange(1,100,3)

In [55]:
dados4

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

###6 – Mostre as raízes quadradas dos valores do NDArray criado no exercícios 5.

In [56]:
dados5=dados4**2

In [57]:
dados5

array([   1,   16,   49,  100,  169,  256,  361,  484,  625,  784,  961,
       1156, 1369, 1600, 1849, 2116, 2401, 2704, 3025, 3364, 3721, 4096,
       4489, 4900, 5329, 5776, 6241, 6724, 7225, 7744, 8281, 8836, 9409])

###7 – Altere a décima posição do NDArray criado no exercício 5 com o dobro do seu valor.

In [58]:
dados5[9]=dados5[9]*2

In [59]:
dados5

array([   1,   16,   49,  100,  169,  256,  361,  484,  625, 1568,  961,
       1156, 1369, 1600, 1849, 2116, 2401, 2704, 3025, 3364, 3721, 4096,
       4489, 4900, 5329, 5776, 6241, 6724, 7225, 7744, 8281, 8836, 9409])

###8 – Execute o comando para criar um Dataframe com os dados disponíveis no notebook.

In [60]:
dados={'Empresa':['Microsoft', 'Google','Univesp','NVData Analytics','Power Bi Experience','USP'], 'Qtde Func':[1000, 1500,500, 100,100,499], 'Site':['https://www.microsoft.com/pt-br','https://www.google.com/','https://univesp.br/','https://www.nvdata.com.br/','https://powerbiexperience.com/pt/','https://www.usp.br/'],'Instagram':['@microsoft','@google','@univespoficial','@nv_data','@leokarpa','@usp.oficial'],'Criação':[1975,1998,2012,2019,2016,1934], 'País':['EUA','EUA','Brasil','Brasil','Brasil','Brasil']}

In [61]:
df1=pd.DataFrame(dados)

In [62]:
df1

Empresa  Qtde Func  ... Criação    País
0            Microsoft       1000  ...    1975     EUA
1               Google       1500  ...    1998     EUA
2              Univesp        500  ...    2012  Brasil
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil
5                  USP        499  ...    1934  Brasil

[6 rows x 6 columns]

###9 – Execute um comando que seja possível identificar qual a média da quantidade de funcionários que as empresas listadas tem. Informe também a soma dos funcionários que as empresas tem.

In [63]:
df2=df1

In [66]:
df2

Empresa  Qtde Func  ... Criação    País
0            Microsoft       1000  ...    1975     EUA
1               Google       1500  ...    1998     EUA
2              Univesp        500  ...    2012  Brasil
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil
5                  USP        499  ...    1934  Brasil

[6 rows x 6 columns]

In [68]:
df2['Qtde Func']

0    1000
1    1500
2     500
3     100
4     100
5     499
Name: Qtde Func, dtype: int64

In [69]:
mean_df = df2['Qtde Func'].mean()

In [70]:
mean_df

616.5

In [99]:
df2['Qtde Func'].sum()

3699

###10 – Mostre as primeiras 3 linhas do dataframe.

In [71]:
df1.head(3)

Empresa  Qtde Func  ... Criação    País
0  Microsoft       1000  ...    1975     EUA
1     Google       1500  ...    1998     EUA
2    Univesp        500  ...    2012  Brasil

[3 rows x 6 columns]

###11 – Mostre as últimas 3 linhas do dataframe.

In [72]:
df1.tail(3)

Empresa  Qtde Func  ... Criação    País
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil
5                  USP        499  ...    1934  Brasil

[3 rows x 6 columns]

###12 – Liste apenas as linhas em que as empresas foram criadas nos últimos 10 anos. Informe a quantidade de registros.

In [77]:
df3=df1[df1['Criação']>(2021-10)]
df3

Empresa  Qtde Func  ... Criação    País
2              Univesp        500  ...    2012  Brasil
3     NVData Analytics        100  ...    2019  Brasil
4  Power Bi Experience        100  ...    2016  Brasil

[3 rows x 6 columns]

In [78]:
df3.count()

Empresa      3
Qtde Func    3
Site         3
Instagram    3
Criação      3
País         3
dtype: int64

In [81]:
df3.shape

(3, 6)

###13 – Vamos imaginar que em todas as empresas exista 1 chefe para cada 23 funcionários. Crie uma coluna que mostre a quantidade de chefes que cada empresa teria e depois informe quantos chefes teríamos ao todo. (os valores não precisam ser números inteiros, é apenas uma estimativa).

In [95]:
df1['Chefes']=df1['Qtde Func']/23

In [96]:
df1

Empresa  Qtde Func  ...    País     Chefes
0            Microsoft       1000  ...     EUA  43.478261
1               Google       1500  ...     EUA  65.217391
2              Univesp        500  ...  Brasil  21.739130
3     NVData Analytics        100  ...  Brasil   4.347826
4  Power Bi Experience        100  ...  Brasil   4.347826
5                  USP        499  ...  Brasil  21.695652

[6 rows x 7 columns]

In [97]:
df1.Chefes.sum()

160.82608695652175