<a href="https://colab.research.google.com/github/GiselleOAlmeida/python-univesp-ciencia-de-dados/blob/main/Semana_3_video_5_Biblioteca_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Semana 2 - vídeo 5
Atividade do vídeo

### Importar **biblioteca**

In [2]:
import numpy as np

Gerar dados aleatórios

Gerar NDArray de 2x3

In [3]:
dados=np.random.rand(2,3)

In [4]:
dados

array([[0.45990354, 0.89538154, 0.40215866],
       [0.74270837, 0.42920988, 0.7746447 ]])

Tipo do array

In [5]:
dados.dtype

dtype('float64')

Tamanho e quantidade de dimensões

In [6]:
dados.shape

(2, 3)

In [7]:
dados.ndim

2

### Criar NDArray usando a função array


#####Ao criar o array a função tenta criar o melhor tipo de dado

In [8]:
lista=[10,15,84,78,15.4]

In [9]:
dados2=np.array(lista)

In [10]:
dados2

array([10. , 15. , 84. , 78. , 15.4])

In [11]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [12]:
dados3=np.array(lista2)

In [13]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

###Outras maneiras de criar arrays

In [3]:
dadoszero=np.zeros(10)

In [4]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
dadoszero2=np.zeros((2,3))

In [6]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
dadosum=np.ones(5)

In [8]:
dadosum

array([1., 1., 1., 1., 1.])

In [9]:
dadossec=np.arange(10)

In [10]:
dadossec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
dadossec2=np.arange(0,20,2)

In [12]:
dadossec2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
dadossec.dtype

dtype('int64')

In [15]:
dadosseqf=dadossec.astype(np.float64)

In [16]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [17]:
dadosseqf.dtype

dtype('float64')

###Aritmética com Arrays

In [18]:
dados4=np.array([[1,2,3],[4,5,6]])

In [19]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [21]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [22]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [23]:
dados5=dados4+dados4

In [24]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

###Indexação

In [27]:
dadossec

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
dadossec[5]

5

#####Diferente de uma lista Python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de banco de dados.

#####Com conjuntos imensos de dados isso é uma grande vantagem em relação à performance.

In [30]:
dadossec[3:6]

array([3, 4, 5])

In [32]:
dadossec[3:6]=20

In [33]:
dadossec

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [34]:
fatiadados=dadossec[2:4]

In [35]:
fatiadados

array([ 2, 20])

In [36]:
fatiadados[1]=2000

In [37]:
fatiadados

array([   2, 2000])

In [38]:
dadossec

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [39]:
fatiadados[:]=333

In [40]:
fatiadados

array([333, 333])

In [41]:
dadossec

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

###Copiar dados

In [48]:
fatia2=dadossec[2:4].copy()

In [49]:
fatia2

array([333, 333])

In [50]:
fatia2[:]=111

In [51]:
fatia2

array([111, 111])

In [52]:
dadossec

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

###Array com mais de uma dimensão

In [57]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
dados6[1:2]

array([[4, 5, 6]])

In [60]:
dados6[1,2]

6

###Máscaras

In [61]:
dadossec

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

In [64]:
mascara=dadossec<100

In [63]:
mascara

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [65]:
dadossec[dadossec<20]=888

In [66]:
dadossec

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

In [72]:
dadossec[dadossec>20]=8.2

In [73]:
dadossec

array([ 8,  8,  8,  8, 20, 20,  8,  8,  8,  8])

In [80]:
dadossec[dadossec<20]=False

In [82]:
dadossec

array([888, 888, 888, 888,  20,  20, 888, 888, 888, 888])

In [85]:
dadossec[2:4]=333

In [86]:
dadossec

array([888, 888, 333, 333,  20,  20, 888, 888, 888, 888])

###Transposição

In [89]:
dados7=np.arange(15).reshape((3,5))

In [90]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [91]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

###Multiplicação de matrizes com DOTS (.dot)

In [93]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

Veja que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outras 